CREATE TABLE flatbed.holidays (
 holiday_id serial PRIMARY KEY,
 country_code VARCHAR (20) NOT NULL,
 holiday_year VARCHAR (4) NOT NULL,
 holiday_date DATE NOT NULL,
 holiday_name VARCHAR (50) NOT NULL,
 active BOOLEAN,
 floating BOOLEAN
);

INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2100', '1/1/2100', 'New Year Day', true , false);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2032', '5/31/2032', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2060', '5/31/2060', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2088', '5/31/2088', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2100', '5/31/2100', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2038', '5/31/2038', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2066', '5/31/2066', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2094', '5/31/2094', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2106', '5/31/2106', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2021', '5/31/2021', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2049', '5/31/2049', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2077', '5/31/2077', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2117', '5/31/2117', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2027', '5/31/2027', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2055', '5/31/2055', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2083', '5/31/2083', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2123', '5/31/2123', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2033', '5/30/2033', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2061', '5/30/2061', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2089', '5/30/2089', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2101', '5/30/2101', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2039', '5/30/2039', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2067', '5/30/2067', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2095', '5/30/2095', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2107', '5/30/2107', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2044', '5/30/2044', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2072', '5/30/2072', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2112', '5/30/2112', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2022', '5/30/2022', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2050', '5/30/2050', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2078', '5/30/2078', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2118', '5/30/2118', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2028', '5/29/2028', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2056', '5/29/2056', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2084', '5/29/2084', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2034', '5/29/2034', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2062', '5/29/2062', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2090', '5/29/2090', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2102', '5/29/2102', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2045', '5/29/2045', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2073', '5/29/2073', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2113', '5/29/2113', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2023', '5/29/2023', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2051', '5/29/2051', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2079', '5/29/2079', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2119', '5/29/2119', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2029', '5/28/2029', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2057', '5/28/2057', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2085', '5/28/2085', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2035', '5/28/2035', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2063', '5/28/2063', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2091', '5/28/2091', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2103', '5/28/2103', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2018', '5/28/2018', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2046', '5/28/2046', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2074', '5/28/2074', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2114', '5/28/2114', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2040', '5/28/2040', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2068', '5/28/2068', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2096', '5/28/2096', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2108', '5/28/2108', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2030', '5/27/2030', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2058', '5/27/2058', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2086', '5/27/2086', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2041', '5/27/2041', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2069', '5/27/2069', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2097', '5/27/2097', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2109', '5/27/2109', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2019', '5/27/2019', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2047', '5/27/2047', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2075', '5/27/2075', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2115', '5/27/2115', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2024', '5/27/2024', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2052', '5/27/2052', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2080', '5/27/2080', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2120', '5/27/2120', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2031', '5/26/2031', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2059', '5/26/2059', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2087', '5/26/2087', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2036', '5/26/2036', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2064', '5/26/2064', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2092', '5/26/2092', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2104', '5/26/2104', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2042', '5/26/2042', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2070', '5/26/2070', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2098', '5/26/2098', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2110', '5/26/2110', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2025', '5/26/2025', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2053', '5/26/2053', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2081', '5/26/2081', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2121', '5/26/2121', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2037', '5/25/2037', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2065', '5/25/2065', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2093', '5/25/2093', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2105', '5/25/2105', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2043', '5/25/2043', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2071', '5/25/2071', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2099', '5/25/2099', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2111', '5/25/2111', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2020', '5/25/2020', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2048', '5/25/2048', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2076', '5/25/2076', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2116', '5/25/2116', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2026', '5/25/2026', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2054', '5/25/2054', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2082', '5/25/2082', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2122', '5/25/2122', 'Memorial Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2100', '7/4/2100', 'Independence Day', true , false);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2043', '9/7/2043', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2071', '9/7/2071', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2099', '9/7/2099', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2020', '9/7/2020', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2048', '9/7/2048', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2076', '9/7/2076', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2026', '9/7/2026', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2054', '9/7/2054', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2082', '9/7/2082', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2037', '9/7/2037', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2065', '9/7/2065', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2093', '9/7/2093', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2105', '9/7/2105', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2021', '9/6/2021', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2049', '9/6/2049', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2077', '9/6/2077', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2027', '9/6/2027', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2055', '9/6/2055', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2083', '9/6/2083', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2032', '9/6/2032', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2060', '9/6/2060', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2088', '9/6/2088', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2100', '9/6/2100', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2038', '9/6/2038', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2066', '9/6/2066', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2094', '9/6/2094', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2106', '9/6/2106', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2044', '9/5/2044', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2072', '9/5/2072', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '1910', '9/5/1910', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2022', '9/5/2022', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2050', '9/5/2050', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2078', '9/5/2078', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2033', '9/5/2033', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2061', '9/5/2061', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2089', '9/5/2089', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2101', '9/5/2101', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2039', '9/5/2039', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2067', '9/5/2067', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2095', '9/5/2095', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2107', '9/5/2107', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2045', '9/4/2045', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2073', '9/4/2073', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '1911', '9/4/1911', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2023', '9/4/2023', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2051', '9/4/2051', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2079', '9/4/2079', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2028', '9/4/2028', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2056', '9/4/2056', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2084', '9/4/2084', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2034', '9/4/2034', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2062', '9/4/2062', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2090', '9/4/2090', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2102', '9/4/2102', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2040', '9/3/2040', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2068', '9/3/2068', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2096', '9/3/2096', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2018', '9/3/2018', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2046', '9/3/2046', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2074', '9/3/2074', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2029', '9/3/2029', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2057', '9/3/2057', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2085', '9/3/2085', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2035', '9/3/2035', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2063', '9/3/2063', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2091', '9/3/2091', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2103', '9/3/2103', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2041', '9/2/2041', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2069', '9/2/2069', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2097', '9/2/2097', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2019', '9/2/2019', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2047', '9/2/2047', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2075', '9/2/2075', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2024', '9/2/2024', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2052', '9/2/2052', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2080', '9/2/2080', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2030', '9/2/2030', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2058', '9/2/2058', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2086', '9/2/2086', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2042', '9/1/2042', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2070', '9/1/2070', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2098', '9/1/2098', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2025', '9/1/2025', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2053', '9/1/2053', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2081', '9/1/2081', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2031', '9/1/2031', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2059', '9/1/2059', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2087', '9/1/2087', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2036', '9/1/2036', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2064', '9/1/2064', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2092', '9/1/2092', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2104', '9/1/2104', 'Labor Day', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2018', '11/22/2018', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2029', '11/22/2029', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2035', '11/22/2035', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2040', '11/22/2040', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2046', '11/22/2046', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2057', '11/22/2057', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2063', '11/22/2063', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2068', '11/22/2068', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2074', '11/22/2074', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2085', '11/22/2085', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2091', '11/22/2091', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2096', '11/22/2096', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2103', '11/22/2103', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2023', '11/23/2023', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2028', '11/23/2028', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2034', '11/23/2034', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2045', '11/23/2045', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2051', '11/23/2051', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2056', '11/23/2056', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2062', '11/23/2062', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2073', '11/23/2073', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2079', '11/23/2079', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2084', '11/23/2084', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2090', '11/23/2090', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2102', '11/23/2102', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2022', '11/24/2022', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2033', '11/24/2033', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2039', '11/24/2039', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2044', '11/24/2044', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2050', '11/24/2050', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2061', '11/24/2061', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2067', '11/24/2067', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2072', '11/24/2072', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2078', '11/24/2078', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2089', '11/24/2089', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2095', '11/24/2095', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2101', '11/24/2101', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2021', '11/25/2021', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2027', '11/25/2027', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2032', '11/25/2032', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2038', '11/25/2038', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2049', '11/25/2049', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2055', '11/25/2055', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2060', '11/25/2060', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2066', '11/25/2066', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2077', '11/25/2077', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2083', '11/25/2083', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2088', '11/25/2088', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2094', '11/25/2094', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2100', '11/25/2100', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2020', '11/26/2020', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2026', '11/26/2026', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2037', '11/26/2037', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2043', '11/26/2043', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2048', '11/26/2048', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2054', '11/26/2054', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2065', '11/26/2065', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2071', '11/26/2071', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2076', '11/26/2076', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2082', '11/26/2082', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2093', '11/26/2093', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2099', '11/26/2099', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2025', '11/27/2025', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2031', '11/27/2031', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2036', '11/27/2036', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2042', '11/27/2042', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2053', '11/27/2053', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2059', '11/27/2059', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2064', '11/27/2064', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2070', '11/27/2070', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2081', '11/27/2081', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2087', '11/27/2087', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2092', '11/27/2092', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2098', '11/27/2098', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2019', '11/28/2019', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2024', '11/28/2024', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2030', '11/28/2030', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2041', '11/28/2041', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2047', '11/28/2047', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2052', '11/28/2052', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2058', '11/28/2058', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2069', '11/28/2069', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2075', '11/28/2075', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2080', '11/28/2080', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2086', '11/28/2086', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2097', '11/28/2097', 'Thanksgiving', true , true);
INSERT INTO flatbed.holidays (country_code, holiday_year, holiday_date, holiday_name, active, floating) VALUES ('USA', '2100', '12/25/2100', 'Christmas Day', true , false);
