//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 04:27:03 PM EEST 
//


package com.pls.ltlrating.soap.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Division.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="Division">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Testing"/>
 *     &lt;enumeration value="All"/>
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="GeneralFreight"/>
 *     &lt;enumeration value="Sameday"/>
 *     &lt;enumeration value="Fastrax"/>
 *     &lt;enumeration value="Intranet"/>
 *     &lt;enumeration value="DayRossGroup"/>
 *     &lt;enumeration value="DayRossDedicated"/>
 *     &lt;enumeration value="Sable"/>
 *     &lt;enumeration value="Ottaway"/>
 *     &lt;enumeration value="BrokerRecruitment"/>
 *     &lt;enumeration value="DRTN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "Division")
@XmlEnum
public enum Division {

    @XmlEnumValue("Testing")
    TESTING("Testing"),
    @XmlEnumValue("All")
    ALL("All"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),
    @XmlEnumValue("GeneralFreight")
    GENERAL_FREIGHT("GeneralFreight"),
    @XmlEnumValue("Sameday")
    SAMEDAY("Sameday"),
    @XmlEnumValue("Fastrax")
    FASTRAX("Fastrax"),
    @XmlEnumValue("Intranet")
    INTRANET("Intranet"),
    @XmlEnumValue("DayRossGroup")
    DAY_ROSS_GROUP("DayRossGroup"),
    @XmlEnumValue("DayRossDedicated")
    DAY_ROSS_DEDICATED("DayRossDedicated"),
    @XmlEnumValue("Sable")
    SABLE("Sable"),
    @XmlEnumValue("Ottaway")
    OTTAWAY("Ottaway"),
    @XmlEnumValue("BrokerRecruitment")
    BROKER_RECRUITMENT("BrokerRecruitment"),
    DRTN("DRTN");
    private final String value;

    Division(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Division fromValue(String v) {
        for (Division c: Division.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
