//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.15 at 06:44:16 PM EET 
//


package com.pls.ltlrating.soap.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Shipment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Shipment">
 *   &lt;complexContent>
 *     &lt;extension base="{http://dayrossgroup.com/web/public/webservices/shipmentServices}DataMapping">
 *       &lt;sequence>
 *         &lt;element name="ShipperAddress" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}ShipmentAddress" minOccurs="0"/>
 *         &lt;element name="ConsigneeAddress" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}ShipmentAddress" minOccurs="0"/>
 *         &lt;element name="BillToAccount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Items" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}ArrayOfShipmentItem" minOccurs="0"/>
 *         &lt;element name="SpecialServices" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}ArrayOfShipmentSpecialService" minOccurs="0"/>
 *         &lt;element name="ShipmentType" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}ShipmentType"/>
 *         &lt;element name="PaymentType" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}PaymentType"/>
 *         &lt;element name="MeasurementSystem" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}MeasurementSystem"/>
 *         &lt;element name="Division" type="{http://dayrossgroup.com/web/public/webservices/shipmentServices}Division"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Shipment", propOrder = {
    "shipperAddress",
    "consigneeAddress",
    "billToAccount",
    "items",
    "specialServices",
    "shipmentType",
    "paymentType",
    "measurementSystem",
    "division"
})
public class Shipment
    extends DataMapping
{

    @XmlElement(name = "ShipperAddress")
    protected ShipmentAddress shipperAddress;
    @XmlElement(name = "ConsigneeAddress")
    protected ShipmentAddress consigneeAddress;
    @XmlElement(name = "BillToAccount")
    protected String billToAccount;
    @XmlElement(name = "Items")
    protected ArrayOfShipmentItem items;
    @XmlElement(name = "SpecialServices")
    protected ArrayOfShipmentSpecialService specialServices;
    @XmlElement(name = "ShipmentType", required = true)
    protected ShipmentType shipmentType;
    @XmlElement(name = "PaymentType", required = true)
    protected PaymentType paymentType;
    @XmlElement(name = "MeasurementSystem", required = true)
    protected MeasurementSystem measurementSystem;
    @XmlElement(name = "Division", required = true)
    protected Division division;

    /**
     * Gets the value of the shipperAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentAddress }
     *     
     */
    public ShipmentAddress getShipperAddress() {
        return shipperAddress;
    }

    /**
     * Sets the value of the shipperAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentAddress }
     *     
     */
    public void setShipperAddress(ShipmentAddress value) {
        this.shipperAddress = value;
    }

    /**
     * Gets the value of the consigneeAddress property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentAddress }
     *     
     */
    public ShipmentAddress getConsigneeAddress() {
        return consigneeAddress;
    }

    /**
     * Sets the value of the consigneeAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentAddress }
     *     
     */
    public void setConsigneeAddress(ShipmentAddress value) {
        this.consigneeAddress = value;
    }

    /**
     * Gets the value of the billToAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToAccount() {
        return billToAccount;
    }

    /**
     * Sets the value of the billToAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToAccount(String value) {
        this.billToAccount = value;
    }

    /**
     * Gets the value of the items property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfShipmentItem }
     *     
     */
    public ArrayOfShipmentItem getItems() {
        return items;
    }

    /**
     * Sets the value of the items property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfShipmentItem }
     *     
     */
    public void setItems(ArrayOfShipmentItem value) {
        this.items = value;
    }

    /**
     * Gets the value of the specialServices property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfShipmentSpecialService }
     *     
     */
    public ArrayOfShipmentSpecialService getSpecialServices() {
        return specialServices;
    }

    /**
     * Sets the value of the specialServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfShipmentSpecialService }
     *     
     */
    public void setSpecialServices(ArrayOfShipmentSpecialService value) {
        this.specialServices = value;
    }

    /**
     * Gets the value of the shipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentType }
     *     
     */
    public ShipmentType getShipmentType() {
        return shipmentType;
    }

    /**
     * Sets the value of the shipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentType }
     *     
     */
    public void setShipmentType(ShipmentType value) {
        this.shipmentType = value;
    }

    /**
     * Gets the value of the paymentType property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentType }
     *     
     */
    public PaymentType getPaymentType() {
        return paymentType;
    }

    /**
     * Sets the value of the paymentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentType }
     *     
     */
    public void setPaymentType(PaymentType value) {
        this.paymentType = value;
    }

    /**
     * Gets the value of the measurementSystem property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurementSystem }
     *     
     */
    public MeasurementSystem getMeasurementSystem() {
        return measurementSystem;
    }

    /**
     * Sets the value of the measurementSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurementSystem }
     *     
     */
    public void setMeasurementSystem(MeasurementSystem value) {
        this.measurementSystem = value;
    }

    /**
     * Gets the value of the division property.
     * 
     * @return
     *     possible object is
     *     {@link Division }
     *     
     */
    public Division getDivision() {
        return division;
    }

    /**
     * Sets the value of the division property.
     * 
     * @param value
     *     allowed object is
     *     {@link Division }
     *     
     */
    public void setDivision(Division value) {
        this.division = value;
    }

}
