//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 04:27:03 PM EEST 
//


package com.pls.ltlrating.soap.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ShipmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Regular"/>
 *     &lt;enumeration value="Return"/>
 *     &lt;enumeration value="ThirdParty"/>
 *     &lt;enumeration value="Exchange"/>
 *     &lt;enumeration value="Quote"/>
 *     &lt;enumeration value="CapacityPRO"/>
 *     &lt;enumeration value="LineH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ShipmentType")
@XmlEnum
public enum ShipmentType {

    @XmlEnumValue("Regular")
    REGULAR("Regular"),
    @XmlEnumValue("Return")
    RETURN("Return"),
    @XmlEnumValue("ThirdParty")
    THIRD_PARTY("ThirdParty"),
    @XmlEnumValue("Exchange")
    EXCHANGE("Exchange"),
    @XmlEnumValue("Quote")
    QUOTE("Quote"),
    @XmlEnumValue("CapacityPRO")
    CAPACITY_PRO("CapacityPRO"),
    @XmlEnumValue("LineH")
    LINE_H("LineH");
    private final String value;

    ShipmentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ShipmentType fromValue(String v) {
        for (ShipmentType c: ShipmentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
