update loads set FINALIZATION_STATUS = 'NF';

update loads set FINALIZATION_STATUS = 'PAH', load_status = 'CD' where load_id in (560, 561);

Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (10,560,null,'CD','Comment 1','A',sysdate,1,to_date('20-OCT-35 09.55.27','DD-MON-RR HH24.MI.SS'),1);
Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (11,560,null,'IF','Comment 2','I',sysdate,1,sysdate,1);
Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (12,560,null,'MD','Comment 3','A',sysdate,1,to_date('20-OCT-34 09.55.27','DD-MON-RR HH24.MI.SS'),1);

Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (13,561,null,'MD','Comment 3','I',sysdate,1,sysdate,1);

---------------------------------------------------

update FINAN_ADJ_ACC_DETAIL set FAA_STATUS = 'ABAA';

update FINAN_ADJ_ACC_DETAIL set FAA_STATUS = 'PAH' where FAA_DETAIL_ID in (3, 6, 7);

Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (14,56,3,'CD','Comment 1','A',sysdate,1,to_date('19-OCT-34 09.55.27','DD-MON-RR HH24.MI.SS'),1);
Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (15,56,3,'IF','Comment 2','I',sysdate,1,sysdate,1);
Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (16,56,3,'MD','Comment 3','A',sysdate,1,to_date('19-OCT-35 09.55.27','DD-MON-RR HH24.MI.SS'),1);

Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (17,59,6,'IF','Comment 2','I',sysdate,1,sysdate,1);
Insert into LD_BILLING_AUDIT_REASONS (LD_BILL_AUDIT_RSN_ID,LOAD_ID,FAA_DETAIL_ID,REASON_CD,COMMENTS,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY)
values (18,59,6,'MD','Comment 3','A',sysdate,1,to_date('18-OCT-35 09.55.27','DD-MON-RR HH24.MI.SS'),1);

