delete from INVOICE_HISTORY;

--successful loads
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (1,1,'CBI',812,null,null,'S',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (2,1,'CBI',813,null,null,'S',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);

--successful adjustments
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (3,1,'CBI',null,1,null,'S',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
update FINAN_ADJ_ACC_DETAIL set SHORT_PAY = 'N' where FAA_DETAIL_ID = 1;
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (4,1,'CBI',null,2,null,'S',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
update FINAN_ADJ_ACC_DETAIL set SHORT_PAY = 'N' where FAA_DETAIL_ID = 2;

--not successful loads
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (5,1,'CBI',814,null,null,'C',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (6,1,'CBI',815,null,null,'F',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (7,1,'CBI',816,null,null,'R',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);

--not successful adjustments
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (8,1,'CBI',null,3,null,'C',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
update FINAN_ADJ_ACC_DETAIL set SHORT_PAY = 'N' where FAA_DETAIL_ID = 3;
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (9,1,'CBI',null,4,null,'F',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
update FINAN_ADJ_ACC_DETAIL set SHORT_PAY = 'N' where FAA_DETAIL_ID = 4;
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (10,1,'CBI',null,5,null,'R',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
update FINAN_ADJ_ACC_DETAIL set SHORT_PAY = 'N' where FAA_DETAIL_ID = 5;
Insert into INVOICE_HISTORY (INVOICE_HISTORY_ID,INVOICE_ID,INVOICE_TYPE,LOAD_ID,FAA_DETAIL_ID,BILLING_STATUS_REASON_CODE,
    RELEASE_STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) values (11,1,'CBI',null,6,null,'S',
    to_date('19-JAN-12 00.00','DD-MON-RR HH24.MI'),2,to_date('12-AUG-12 00.00','DD-MON-RR HH24.MI'),2);
update FINAN_ADJ_ACC_DETAIL set SHORT_PAY = 'Y' where FAA_DETAIL_ID = 6;