--PLS user
INSERT INTO FLATBED.USERS (PERSON_ID,ORG_ID,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,USERID,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) 
    VALUES (-100,38941,'test.email','T','T','Test1','A', SYSDATE ,0,SYSDATE,0);


-- Two customer user
INSERT INTO FLATBED.USERS (PERSON_ID,ORG_ID,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,USERID,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) 
    VALUES (-98,1,'test.email','T','T','Test3','A', SYSDATE ,0,SYSDATE,0);
INSERT INTO FLATBED.USERS (PERSON_ID,ORG_ID,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,USERID,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) 
    VALUES (-97,2,'test.email','T','T','Test4','A', SYSDATE ,0,SYSDATE,0);


-- OrgUser record for the first PLS user
INSERT INTO FLATBED.ORGANIZATION_USERS (ORG_USER_ID, PERSON_ID,ORG_ID,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY,ORG_TYPE) 
    VALUES (-100, -100, 1,'A', SYSDATE ,0,SYSDATE,0, 'SHIPPER');