--Two inactive PLS users
INSERT INTO FLATBED.USERS (PERSON_ID,ORG_ID,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,USERID,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) 
    VALUES (-100,38941,'test.email','T','T','Test1','I', SYSDATE ,0,SYSDATE,0);

INSERT INTO FLATBED.USERS (PERSON_ID,ORG_ID,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,USERID,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) 
    VALUES (-99,38941,'test.email','T','T','Test2','I', SYSDATE ,0,SYSDATE,0);
