-- One customer user
INSERT INTO FLATBED.USERS (PERSON_ID,ORG_ID,EMAIL_ADDRESS,FIRST_NAME,LAST_NAME,USERID,STATUS,DATE_CREATED,CREATED_BY,DATE_MODIFIED,MODIFIED_BY) 
    VALUES (-98,1,'test.email','T','T','Test3','A', SYSDATE ,0,SYSDATE,0);