<#include "header.ftl">

<h3>Hello, ${user.firstName} ${user.lastName}!</h3>
    <p>This email message has been generated by Admin User's request to reset your password.</p>
    <p>Your User ID is ${user.login}</p>
    <p>Your current password is ${newPassword}</p>
    <p>Please, change this password after <a href="${clientUrl}">logging in</a>.</p>
    <p>Sincerely, PLS Notification</p>

<#include "footer.ftl">
