SET search_path = flatbed, pg_catalog;

ALTER TABLE ONLY address_notifications ADD CONSTRAINT address_notifications_pk PRIMARY KEY (address_notification_id);
ALTER TABLE ONLY addresses ADD CONSTRAINT addresses_pkey PRIMARY KEY (address_id);
ALTER TABLE ONLY ap_terms ADD CONSTRAINT ap_terms_pkey PRIMARY KEY (term_id, sequence_num);
ALTER TABLE ONLY api_exceptions ADD CONSTRAINT api_exceptions_pkey PRIMARY KEY (api_exception_id);
ALTER TABLE ONLY api_log ADD CONSTRAINT api_log_pkey PRIMARY KEY (api_log_id);
ALTER TABLE ONLY api_metadata ADD CONSTRAINT api_metadata_pkey PRIMARY KEY (api_metadata_id);
ALTER TABLE ONLY api_types ADD CONSTRAINT api_types_pkey PRIMARY KEY (api_type_id);
ALTER TABLE ONLY audit_shipment_cost_details ADD CONSTRAINT audit_shipment_cost_details_pkey PRIMARY KEY (add_detail_id);
ALTER TABLE ONLY bill_to_default_values ADD CONSTRAINT bill_to_default_values_pkey PRIMARY KEY (bill_to_default_value_id);
ALTER TABLE ONLY bill_to ADD CONSTRAINT bill_to_org_id_name_key UNIQUE (org_id, name) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY bill_to ADD CONSTRAINT bill_to_org_id_name_key1 UNIQUE (org_id, name) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY bill_to ADD CONSTRAINT bill_to_pkey PRIMARY KEY (bill_to_id);
ALTER TABLE ONLY bill_to_req_doc ADD CONSTRAINT bill_to_req_doc_pkey PRIMARY KEY (bill_to_req_doc_id);
ALTER TABLE ONLY bill_to_req_field ADD CONSTRAINT bill_to_req_field_pkey PRIMARY KEY (bill_to_req_field_id);
ALTER TABLE ONLY bill_to_threshold_settings ADD CONSTRAINT bill_to_threshold_settings_pkey PRIMARY KEY (bill_to_audit_threshold_id);
ALTER TABLE ONLY billing_invoice_node ADD CONSTRAINT billing_invoice_node_bill_to_id_customer_number_customer_i_key1 UNIQUE (bill_to_id, customer_number, customer_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY billing_invoice_node ADD CONSTRAINT billing_invoice_node_bill_to_id_customer_number_customer_id_key UNIQUE (bill_to_id, customer_number, customer_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY billing_invoice_node ADD CONSTRAINT billing_invoice_node_bill_to_id_network_id_key UNIQUE (bill_to_id, network_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY billing_invoice_node ADD CONSTRAINT billing_invoice_node_bill_to_id_network_id_key1 UNIQUE (bill_to_id, network_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY billing_invoice_node ADD CONSTRAINT billing_invoice_node_pkey PRIMARY KEY (billing_node_id);
ALTER TABLE ONLY billing_status_reason_codes ADD CONSTRAINT billing_status_reason_codes_pkey PRIMARY KEY (status_reason);
ALTER TABLE ONLY carriers ADD CONSTRAINT carriers_org_id_network_id_key UNIQUE (org_id, network_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY carriers ADD CONSTRAINT carriers_org_id_network_id_key1 UNIQUE (org_id, network_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY carriers ADD CONSTRAINT carriers_pkey PRIMARY KEY (carrier_id); 
ALTER TABLE ONLY cap_category_types ADD CONSTRAINT cap_category_types_pkey PRIMARY KEY (category);
ALTER TABLE ONLY capabilities ADD CONSTRAINT capabilities_description_key UNIQUE (description) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY capabilities ADD CONSTRAINT capabilities_description_key1 UNIQUE (description) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY capabilities ADD CONSTRAINT capabilities_name_key UNIQUE (name) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY capabilities ADD CONSTRAINT capabilities_name_key1 UNIQUE (name) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY capabilities ADD CONSTRAINT capabilities_pkey PRIMARY KEY (capability_id);
ALTER TABLE ONLY carr_edi_cost_types ADD CONSTRAINT carr_edi_cost_types_pkey PRIMARY KEY (carr_edi_cost_type_id);
ALTER TABLE ONLY carrier_invoice_addr_details ADD CONSTRAINT carrier_invoice_addr_details_pkey PRIMARY KEY (addr_det_id);
ALTER TABLE ONLY carrier_invoice_cost_items ADD CONSTRAINT carrier_invoice_cost_items_pkey PRIMARY KEY (invoice_cost_detail_item_id);
ALTER TABLE ONLY carrier_invoice_details ADD CONSTRAINT carrier_invoice_details_pkey PRIMARY KEY (invoice_det_id);
ALTER TABLE ONLY carrier_invoice_line_items ADD CONSTRAINT carrier_invoice_line_items_pkey PRIMARY KEY (invoice_line_item_id);
ALTER TABLE ONLY carrier_invoice_reason_links ADD CONSTRAINT carrier_invoice_reason_links_pkey PRIMARY KEY (link_id);
ALTER TABLE ONLY carrier_invoice_reasons ADD CONSTRAINT carrier_invoice_reasons_pkey PRIMARY KEY (reason_id);
ALTER TABLE ONLY company_codes ADD CONSTRAINT company_codes_pkey PRIMARY KEY (company_code);
ALTER TABLE ONLY container_types ADD CONSTRAINT container_types_pkey PRIMARY KEY (container_cd); 
ALTER TABLE ONLY customer_invoice_errors ADD CONSTRAINT customer_invoice_errors_pkey PRIMARY KEY (id);
ALTER TABLE ONLY dot_region_fuel ADD CONSTRAINT dot_region_fuel_pkey PRIMARY KEY (dot_region_fuel_id);
ALTER TABLE ONLY dot_regions ADD CONSTRAINT dot_regions_pkey PRIMARY KEY (dot_region_id);
ALTER TABLE ONLY edi_load_data ADD CONSTRAINT edi_load_data_pkey PRIMARY KEY (gs);
ALTER TABLE ONLY edi ADD CONSTRAINT edi_pkey PRIMARY KEY (edi_id);
ALTER TABLE ONLY edi_qualifiers ADD CONSTRAINT edi_qualifiers_pkey PRIMARY KEY (edi_qual_id);
ALTER TABLE ONLY edi_qualifiers ADD CONSTRAINT edi_qualifiers_transaction_set_id_org_id_element_pls_refer_key1 UNIQUE (transaction_set_id, org_id, element, pls_reference) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY edi_qualifiers ADD CONSTRAINT edi_qualifiers_transaction_set_id_org_id_element_pls_refere_key UNIQUE (transaction_set_id, org_id, element, pls_reference) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY edi_rejected_customers ADD CONSTRAINT edi_rejected_customers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY edi_settings ADD CONSTRAINT edi_settings_pkey PRIMARY KEY (edi_settings_id);
ALTER TABLE ONLY email_history_attachment ADD CONSTRAINT email_history_attachment_pkey PRIMARY KEY (email_history_attachment_id);
ALTER TABLE ONLY email_history_load ADD CONSTRAINT email_history_load_pkey PRIMARY KEY (email_history_load_id);
ALTER TABLE ONLY email_history ADD CONSTRAINT email_history_pkey PRIMARY KEY (email_history_id);
ALTER TABLE ONLY fa_accessorials ADD CONSTRAINT fa_accessorials_pkey PRIMARY KEY (accessorial_id);
ALTER TABLE ONLY fa_financial_analysis ADD CONSTRAINT fa_financial_analysis_pkey PRIMARY KEY (analysis_id);
ALTER TABLE ONLY fa_input_details ADD CONSTRAINT fa_input_details_pkey PRIMARY KEY (input_detail_id);
ALTER TABLE ONLY fa_materials ADD CONSTRAINT fa_materials_pkey PRIMARY KEY (material_id);
ALTER TABLE ONLY fa_output_details ADD CONSTRAINT fa_output_details_pkey PRIMARY KEY (output_detail_id);
ALTER TABLE ONLY fa_tariffs ADD CONSTRAINT fa_tariffs_pkey PRIMARY KEY (tariff_id);
ALTER TABLE ONLY finan_account_payables ADD CONSTRAINT finan_account_payables_pkey PRIMARY KEY (finan_ap_id);
ALTER TABLE ONLY finan_account_receivables ADD CONSTRAINT finan_account_receivables_pkey PRIMARY KEY (finan_ar_id);
ALTER TABLE ONLY finan_adj_acc_detail_addl_info ADD CONSTRAINT finan_adj_acc_detail_addl_info_pkey PRIMARY KEY (faa_detail_addl_id);
ALTER TABLE ONLY finan_adj_acc_detail ADD CONSTRAINT finan_adj_acc_detail_pkey PRIMARY KEY (faa_detail_id);
ALTER TABLE ONLY finan_adj_acc_detail_prod_info ADD CONSTRAINT finan_adj_acc_detail_prod_info_pkey PRIMARY KEY (faa_detail_addl_prod_id);
ALTER TABLE ONLY finan_adj_acc_reasons ADD CONSTRAINT finan_adj_acc_reasons_pkey PRIMARY KEY (adj_acc_type_id);
ALTER TABLE ONLY finan_ap_details ADD CONSTRAINT finan_ap_details_pkey PRIMARY KEY (finan_ap_detail_id);
ALTER TABLE ONLY finan_ar_details ADD CONSTRAINT finan_ar_details_pkey PRIMARY KEY (finan_ar_detail_id);
ALTER TABLE ONLY finan_billers ADD CONSTRAINT finan_billers_pkey PRIMARY KEY (finan_biller_id);
ALTER TABLE ONLY finan_int_responses ADD CONSTRAINT finan_int_responses_pkey PRIMARY KEY (finan_int_resp_id);
ALTER TABLE ONLY finan_requests ADD CONSTRAINT finan_requests_pkey PRIMARY KEY (request_id);
ALTER TABLE ONLY freight_bill_pay_to ADD CONSTRAINT freight_bill_pay_to_pkey PRIMARY KEY (frt_bill_pay_to_id);
ALTER TABLE ONLY group_capabilities ADD CONSTRAINT group_capabilities_group_id_capability_id_key UNIQUE (group_id, capability_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY group_capabilities ADD CONSTRAINT group_capabilities_group_id_capability_id_key1 UNIQUE (group_id, capability_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY group_capabilities ADD CONSTRAINT group_capabilities_pkey PRIMARY KEY (group_capability_id);
ALTER TABLE ONLY groups ADD CONSTRAINT groups_pkey PRIMARY KEY (group_id);
ALTER TABLE ONLY image_document_type ADD CONSTRAINT image_document_type_document_type_key UNIQUE (document_type) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY image_document_type ADD CONSTRAINT image_document_type_document_type_key1 UNIQUE (document_type) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY image_document_type ADD CONSTRAINT image_document_type_pkey PRIMARY KEY (image_doc_type_id);
ALTER TABLE ONLY image_metadata ADD CONSTRAINT image_metadata_pkey PRIMARY KEY (image_meta_id);
ALTER TABLE ONLY int_audit_details ADD CONSTRAINT int_audit_details_pkey PRIMARY KEY (audit_detail_id);
ALTER TABLE ONLY int_audit ADD CONSTRAINT int_audit_pkey PRIMARY KEY (audit_id);
ALTER TABLE ONLY invoice_history ADD CONSTRAINT invoice_history_pkey PRIMARY KEY (invoice_history_id);
ALTER TABLE ONLY invoice_settings ADD CONSTRAINT invoice_settings_pkey PRIMARY KEY (invoice_settings_id);
ALTER TABLE ONLY ld_bill_audit_reason_codes ADD CONSTRAINT ld_bill_audit_reason_codes_pkey PRIMARY KEY (reason_cd);
ALTER TABLE ONLY ld_billing_audit_reasons ADD CONSTRAINT ld_billing_audit_reasons_pkey PRIMARY KEY (ld_bill_audit_rsn_id);
ALTER TABLE ONLY ld_inv_audit_info ADD CONSTRAINT ld_inv_audit_info_pkey PRIMARY KEY (ld_inv_audit_info_id);
ALTER TABLE ONLY load_additional_fields ADD CONSTRAINT load_additional_fields_pkey PRIMARY KEY (load_additional_fields_id);
ALTER TABLE ONLY load_addl_info ADD CONSTRAINT load_addl_info_load_id_key UNIQUE (load_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY load_addl_info ADD CONSTRAINT load_addl_info_load_id_key1 UNIQUE (load_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY load_addl_info ADD CONSTRAINT load_addl_info_pkey PRIMARY KEY (load_addl_info_id);
ALTER TABLE ONLY load_billing_history ADD CONSTRAINT load_billing_history_pkey PRIMARY KEY (history_id);
ALTER TABLE ONLY load_details ADD CONSTRAINT load_details_pkey PRIMARY KEY (load_detail_id);
ALTER TABLE ONLY load_dispatch_information ADD CONSTRAINT load_dispatch_information_pkey PRIMARY KEY (load_dispatch_info_id);
ALTER TABLE ONLY load_finalization_history ADD CONSTRAINT load_finalization_history_pkey PRIMARY KEY (lfh_id);
ALTER TABLE ONLY load_generic_event_types ADD CONSTRAINT load_generic_event_types_pkey PRIMARY KEY (event_type);
ALTER TABLE ONLY load_generic_events_data ADD CONSTRAINT load_generic_events_data_pkey PRIMARY KEY (event_id, ordinal);
ALTER TABLE ONLY load_generic_events ADD CONSTRAINT load_generic_events_pkey PRIMARY KEY (event_id);
ALTER TABLE ONLY load_job_numbers ADD CONSTRAINT load_job_numbers_pkey PRIMARY KEY (load_job_number_id);
ALTER TABLE ONLY load_materials ADD CONSTRAINT load_materials_pkey PRIMARY KEY (load_material_id);
ALTER TABLE ONLY load_notifications ADD CONSTRAINT load_notifications_load_id_notification_type_email_address_key UNIQUE (load_id, notification_type, email_address) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY load_notifications ADD CONSTRAINT load_notifications_pkey PRIMARY KEY (load_notification_id);
ALTER TABLE ONLY load_pric_material_dtls ADD CONSTRAINT load_pric_material_dtls_pkey PRIMARY KEY (load_pric_material_dtls_id);
ALTER TABLE ONLY load_pricing_details ADD CONSTRAINT load_pricing_details_pkey PRIMARY KEY (load_pricing_detail_id);
ALTER TABLE ONLY load_search_data ADD CONSTRAINT load_search_data_pkey PRIMARY KEY (load_id);
ALTER TABLE ONLY load_tracking ADD CONSTRAINT load_tracking_pkey PRIMARY KEY (tracking_id);
ALTER TABLE ONLY load_tracking_status_types ADD CONSTRAINT load_tracking_status_types_pkey PRIMARY KEY (track_status_code, source);
ALTER TABLE ONLY load_trk_status_reason_types ADD CONSTRAINT load_trk_status_reason_types_pkey PRIMARY KEY (reason_code, source);
ALTER TABLE ONLY loads_ltl_accessorials ADD CONSTRAINT loads_ltl_accessorials_pkey PRIMARY KEY (ltl_accessorial_id);
ALTER TABLE ONLY loads ADD CONSTRAINT loads_pkey PRIMARY KEY (load_id);
ALTER TABLE ONLY lookup_value ADD CONSTRAINT lookup_value_pkey PRIMARY KEY (lookup_value_id);
ALTER TABLE ONLY lost_sav_opp_rpt_acc ADD CONSTRAINT lost_sav_opp_rpt_acc_pkey PRIMARY KEY (lso_rpt_accessorial_id);
ALTER TABLE ONLY lost_sav_opp_rpt_data ADD CONSTRAINT lost_sav_opp_rpt_data_pkey PRIMARY KEY (lso_rpt_data_id);
ALTER TABLE ONLY lost_sav_opp_rpt_materials ADD CONSTRAINT lost_sav_opp_rpt_materials_pkey PRIMARY KEY (lso_rpt_material_id); 
ALTER TABLE ONLY ltl_acc_geo_services ADD CONSTRAINT ltl_acc_geo_services_pkey PRIMARY KEY (ltl_acc_geo_service_id);
ALTER TABLE ONLY ltl_accessorials ADD CONSTRAINT ltl_accessorials_pkey PRIMARY KEY (ltl_accessorial_id);
ALTER TABLE ONLY ltl_bk_lane_geo_serv_dtls ADD CONSTRAINT ltl_bk_lane_geo_serv_dtls_pkey PRIMARY KEY (ltl_bk_lane_geo_serv_dtl_id);
ALTER TABLE ONLY ltl_block_carr_geo_services ADD CONSTRAINT ltl_block_carr_geo_services_pkey PRIMARY KEY (ltl_block_carr_geo_service_id);
ALTER TABLE ONLY ltl_carrier_liabilities ADD CONSTRAINT ltl_carrier_liabilities_pkey PRIMARY KEY (ltl_carrier_liability_id);
ALTER TABLE ONLY ltl_cust_hide_pric_details ADD CONSTRAINT ltl_cust_hide_pric_details_pkey PRIMARY KEY (cust_hide_pric_detail_id);
ALTER TABLE ONLY ltl_fak_map ADD CONSTRAINT ltl_fak_map_pkey PRIMARY KEY (ltl_fak_map_id);
ALTER TABLE ONLY ltl_fuel_geo_services ADD CONSTRAINT ltl_fuel_geo_services_pkey PRIMARY KEY (ltl_fuel_geo_service_id);
ALTER TABLE ONLY ltl_fuel ADD CONSTRAINT ltl_fuel_pkey PRIMARY KEY (ltl_fuel_id);
ALTER TABLE ONLY ltl_fuel_surcharge ADD CONSTRAINT ltl_fuel_surcharge_pkey PRIMARY KEY (ltl_fuel_surcharge_id);
ALTER TABLE ONLY ltl_guaran_block_dest ADD CONSTRAINT ltl_guaran_block_dest_pkey PRIMARY KEY (ltl_guaran_block_dest_id);
ALTER TABLE ONLY ltl_guaranteed_price ADD CONSTRAINT ltl_guaranteed_price_pkey PRIMARY KEY (ltl_guaranteed_price_id);
ALTER TABLE ONLY ltl_lookup_value ADD CONSTRAINT ltl_lookup_value_ltl_lookup_group_ltl_lookup_value_key UNIQUE (ltl_lookup_group, ltl_lookup_value) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY ltl_lookup_value ADD CONSTRAINT ltl_lookup_value_pkey PRIMARY KEY (ltl_lookup_value_id);
ALTER TABLE ONLY ltl_org_block_lane ADD CONSTRAINT ltl_org_block_lane_pkey PRIMARY KEY (ltl_block_lane_id);
ALTER TABLE ONLY ltl_pallet_pric_details ADD CONSTRAINT ltl_pallet_pric_details_pkey PRIMARY KEY (ltl_pallet_pric_det_id);
ALTER TABLE ONLY ltl_pric_geo_serv_dtls ADD CONSTRAINT ltl_pric_geo_serv_dtls_pkey PRIMARY KEY (ltl_pric_geo_serv_dtl_id);
ALTER TABLE ONLY ltl_pric_nw_dflt_margin ADD CONSTRAINT ltl_pric_nw_dflt_margin_pkey PRIMARY KEY (nw_dflt_mrgn_id);
ALTER TABLE ONLY ltl_pric_prop_cost_details ADD CONSTRAINT ltl_pric_prop_cost_details_pkey PRIMARY KEY (ltl_pric_prop_cost_det_id);
ALTER TABLE ONLY ltl_pric_prop_materials ADD CONSTRAINT ltl_pric_prop_materials_pkey PRIMARY KEY (ltl_pric_prop_mat_id);
ALTER TABLE ONLY ltl_pricing_api_address_crit ADD CONSTRAINT ltl_pricing_api_address_crit_pkey PRIMARY KEY (ltl_pricing_api_address_id);
ALTER TABLE ONLY ltl_pricing_api_crit ADD CONSTRAINT ltl_pricing_api_crit_pkey PRIMARY KEY (ltl_pricing_api_crit_id);
ALTER TABLE ONLY ltl_pricing_api_materials_crit ADD CONSTRAINT ltl_pricing_api_materials_crit_pkey PRIMARY KEY (ltl_pricing_api_material_id);
ALTER TABLE ONLY ltl_pricing_appl_cust ADD CONSTRAINT ltl_pricing_appl_cust_pkey PRIMARY KEY (ltl_appl_cust_id);
ALTER TABLE ONLY ltl_pricing_blocked_cust ADD CONSTRAINT ltl_pricing_blocked_cust_pkey PRIMARY KEY (ltl_blocked_cust_id);
ALTER TABLE ONLY ltl_pricing_details ADD CONSTRAINT ltl_pricing_details_pkey PRIMARY KEY (ltl_pricing_detail_id);
ALTER TABLE ONLY ltl_pricing_geo_services ADD CONSTRAINT ltl_pricing_geo_services_pkey PRIMARY KEY (ltl_pricing_geo_service_id);
ALTER TABLE ONLY ltl_pricing_notes ADD CONSTRAINT ltl_pricing_notes_pkey PRIMARY KEY (ltl_pricing_note_id);
ALTER TABLE ONLY ltl_pricing_profile_details ADD CONSTRAINT ltl_pricing_profile_details_pkey PRIMARY KEY (ltl_pric_prof_detail_id);
ALTER TABLE ONLY ltl_pricing_profile ADD CONSTRAINT ltl_pricing_profile_pkey PRIMARY KEY (ltl_pricing_profile_id);
ALTER TABLE ONLY ltl_pricing_proposals ADD CONSTRAINT ltl_pricing_proposals_pkey PRIMARY KEY (ltl_pric_proposal_id);
ALTER TABLE ONLY ltl_pricing_terminal_info ADD CONSTRAINT ltl_pricing_terminal_info_pkey PRIMARY KEY (ltl_terminal_info_id);
ALTER TABLE ONLY ltl_pricing_third_party_info ADD CONSTRAINT ltl_pricing_third_party_info_pkey PRIMARY KEY (ltl_third_party_info_id);
ALTER TABLE ONLY ltl_pricing_types ADD CONSTRAINT ltl_pricing_types_pkey PRIMARY KEY (ltl_pricing_type);
ALTER TABLE ONLY ltl_product ADD CONSTRAINT ltl_product_pkey PRIMARY KEY (ltl_product_id);
ALTER TABLE ONLY ltl_rating_carrier_types ADD CONSTRAINT ltl_rating_carrier_types_pkey PRIMARY KEY (ltl_rating_carrier_type);
ALTER TABLE ONLY ltl_zone_geo_services ADD CONSTRAINT ltl_zone_geo_services_pkey PRIMARY KEY (ltl_zone_geo_service_id);
ALTER TABLE ONLY ltl_zones ADD CONSTRAINT ltl_zones_pkey PRIMARY KEY (ltl_zone_id);
ALTER TABLE ONLY manual_bol_address ADD CONSTRAINT manual_bol_address_pkey PRIMARY KEY (id);
ALTER TABLE ONLY manual_bol_job_numbers ADD CONSTRAINT manual_bol_job_numbers_pkey PRIMARY KEY (manual_bol_job_number_id);
ALTER TABLE ONLY manual_bol_materials ADD CONSTRAINT manual_bol_materials_pkey PRIMARY KEY (manual_bol_material_id);
ALTER TABLE ONLY manual_bol ADD CONSTRAINT manual_bol_pkey PRIMARY KEY (manual_bol_id);
ALTER TABLE ONLY network_users ADD CONSTRAINT network_users_pkey PRIMARY KEY (network_user_id);
ALTER TABLE ONLY networks ADD CONSTRAINT networks_pkey PRIMARY KEY (network_id);
ALTER TABLE ONLY notes ADD CONSTRAINT notes_pkey PRIMARY KEY (note_id);
ALTER TABLE ONLY notification_types ADD CONSTRAINT notification_types_pkey PRIMARY KEY (notification_type);
ALTER TABLE ONLY org_frt_bill_pay_to ADD CONSTRAINT org_frt_bill_pay_to_pkey PRIMARY KEY (org_frt_bill_pay_to_id);
ALTER TABLE ONLY org_services ADD CONSTRAINT org_services_pkey PRIMARY KEY (org_service_id);
ALTER TABLE ONLY organization_api_details ADD CONSTRAINT organization_api_details_org_id_key UNIQUE (org_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY organization_api_details ADD CONSTRAINT organization_api_details_pkey PRIMARY KEY (organization_api_detail_id);
ALTER TABLE ONLY organization_locations ADD CONSTRAINT organization_locations_org_id_location_id_key UNIQUE (org_id, location_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY organization_locations ADD CONSTRAINT organization_locations_pkey PRIMARY KEY (location_id);
ALTER TABLE ONLY organization_phones ADD CONSTRAINT organization_phones_org_id_phone_type_location_id_key UNIQUE (org_id, phone_type, location_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY organization_phones ADD CONSTRAINT organization_phones_pkey PRIMARY KEY (org_phone_id);
ALTER TABLE ONLY organization_pricing ADD CONSTRAINT organization_pricing_pkey PRIMARY KEY (org_id);
ALTER TABLE ONLY organization_users ADD CONSTRAINT organization_users_org_id_person_id_location_id_key UNIQUE (org_id, person_id, location_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY organization_users ADD CONSTRAINT organization_users_pkey PRIMARY KEY (org_user_id);
ALTER TABLE ONLY organizations ADD CONSTRAINT organizations_pkey PRIMARY KEY (org_id);
ALTER TABLE ONLY organizations ADD CONSTRAINT organizations_scac_key UNIQUE (scac) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY outbound_queue_map ADD CONSTRAINT outbound_queue_map_pkey PRIMARY KEY (org_id);
ALTER TABLE ONLY package_types ADD CONSTRAINT package_types_pkey PRIMARY KEY (package_type);
ALTER TABLE ONLY paperwork_hold_documents ADD CONSTRAINT paperwork_hold_documents_pkey PRIMARY KEY (paperwork_hold_document_id);
ALTER TABLE ONLY phones ADD CONSTRAINT phones_pkey PRIMARY KEY (phone_id);
ALTER TABLE ONLY pls_customer_terms ADD CONSTRAINT pls_customer_terms_pkey PRIMARY KEY (term_id);
ALTER TABLE ONLY prepaid_details ADD CONSTRAINT prepaid_details_pkey PRIMARY KEY (id);
ALTER TABLE ONLY promo_code_ae ADD CONSTRAINT promo_code_ae_pkey PRIMARY KEY (promo_code_ae_id);
ALTER TABLE ONLY promo_code_load ADD CONSTRAINT promo_code_load_pkey PRIMARY KEY (promo_code_load_id);
ALTER TABLE ONLY routes ADD CONSTRAINT routes_pkey PRIMARY KEY (route_id);
ALTER TABLE ONLY saved_quote_materials ADD CONSTRAINT saved_quote_materials_pkey PRIMARY KEY (quote_material_id);
ALTER TABLE ONLY saved_quote_pric_dtls ADD CONSTRAINT saved_quote_pric_dtls_pkey PRIMARY KEY (saved_quote_pric_dtls_id);
ALTER TABLE ONLY saved_quote_pric_mat_dtls ADD CONSTRAINT saved_quote_pric_mat_dtls_pkey PRIMARY KEY (saved_quote_pric_mat_dtls_id);
ALTER TABLE ONLY saved_quotes ADD CONSTRAINT saved_quotes_pkey PRIMARY KEY (quote_id);
ALTER TABLE ONLY shipment_alerts ADD CONSTRAINT shipment_alerts_pkey PRIMARY KEY (alert_id);
ALTER TABLE ONLY smc3_error_codes ADD CONSTRAINT smc3_error_codes_pkey PRIMARY KEY (smc3_error_code_id);
ALTER TABLE ONLY smc3_tariffs ADD CONSTRAINT smc3_tariffs_pkey PRIMARY KEY (smc3_tariff_id);
ALTER TABLE ONLY states ADD CONSTRAINT states_pkey PRIMARY KEY (state_code, country_code);
ALTER TABLE ONLY sv_qt_cost_detail_items ADD CONSTRAINT sv_qt_cost_detail_items_pkey PRIMARY KEY (item_id);
ALTER TABLE ONLY sv_qt_cost_details ADD CONSTRAINT sv_qt_cost_details_pkey PRIMARY KEY (quote_cost_detail_id);
ALTER TABLE ONLY sv_qt_ltl_accessorials ADD CONSTRAINT sv_qt_ltl_accessorials_pkey PRIMARY KEY (accessorial_id);
ALTER TABLE ONLY team ADD CONSTRAINT team_pkey PRIMARY KEY (team_id); 
ALTER TABLE ONLY user_addl_contact_info ADD CONSTRAINT user_addl_contact_info_pkey PRIMARY KEY (usr_addl_cnt_info_id);
ALTER TABLE ONLY user_address_book ADD CONSTRAINT user_address_book_pkey PRIMARY KEY (addr_book_id);
ALTER TABLE ONLY user_addresses ADD CONSTRAINT user_addresses_person_id_org_user_id_key UNIQUE (person_id, org_user_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY user_addresses ADD CONSTRAINT user_addresses_pkey PRIMARY KEY (user_address_id);
ALTER TABLE ONLY user_capabilities_xref ADD CONSTRAINT user_capabilities_xref_person_id_capability_id_key UNIQUE (person_id, capability_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY user_capabilities_xref ADD CONSTRAINT user_capabilities_xref_pkey PRIMARY KEY (user_capability_id);
ALTER TABLE ONLY user_customer ADD CONSTRAINT user_customer_pkey PRIMARY KEY (user_customer_id);
ALTER TABLE ONLY user_groups ADD CONSTRAINT user_groups_group_id_person_id_key UNIQUE (group_id, person_id) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY user_groups ADD CONSTRAINT user_groups_pkey PRIMARY KEY (user_group_id);
ALTER TABLE ONLY user_notifications ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (user_notification_id);
ALTER TABLE ONLY user_phones ADD CONSTRAINT user_phones_person_id_org_user_id_phone_type_key UNIQUE (person_id, org_user_id, phone_type) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY user_phones ADD CONSTRAINT user_phones_pkey PRIMARY KEY (user_phone_id);
ALTER TABLE ONLY users ADD CONSTRAINT users_pkey PRIMARY KEY (person_id);
ALTER TABLE ONLY users ADD CONSTRAINT users_userid_key UNIQUE (userid) deferrable INITIALLY DEFERRED;
ALTER TABLE ONLY address_notifications ADD CONSTRAINT notification_types_addr_fk FOREIGN KEY (notification_type) REFERENCES notification_types(notification_type) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ONLY address_notifications ADD CONSTRAINT user_addr_book_addr_fk FOREIGN KEY (user_address_book_id) REFERENCES user_address_book(addr_book_id) DEFERRABLE INITIALLY DEFERRED;
SET search_path = public;
commit;
