package com.pls.user.service.impl.email;

import java.util.Arrays;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.Spy;
import org.mockito.runners.MockitoJUnitRunner;
import org.springframework.context.support.ClassPathXmlApplicationContext;

import com.pls.core.domain.enums.EmailType;
import com.pls.core.domain.user.UserEntity;
import com.pls.core.email.EmailTemplates;
import com.pls.email.EmailTemplateRenderer;
import com.pls.email.producer.EmailMessageProducer;

/**
 * Class for testing of change password email.
 * 
 * @author Stas Norochevskiy
 */
@RunWith(MockitoJUnitRunner.class)
public class UserManagementEmailSenderTest {
    private static final String NEW_PASSWORD = "NEW_PASSWORD" + Math.random();
    private static final String EMAIL = "EMAIL" + Math.random();
    private static final String FIRST_NAME = "FIRST_NAME" + Math.random();
    private static final String LAST_NAME = "LAST_NAME" + Math.random();

    static ClassPathXmlApplicationContext appContext = new ClassPathXmlApplicationContext("classpath*:**/userMgmtTestApplicationContext.xml");
    private static final String APP_URL = appContext.getBeanFactory().resolveEmbeddedValue("${pls.client.index.url}");

    @Mock
    private EmailMessageProducer emailMessageProducer;

    @Spy
    private EmailTemplateRenderer emailTemplateRenderer;

    @InjectMocks
    private UserManagementEmailSender userManagementEmailSender;

    @Before
    public void init() {
        userManagementEmailSender.setClientUrl(APP_URL);
    }

    @Test@Ignore
    public void shouldSendUserRegistredEmail() throws Exception {
        final UserEntity user = getUser();

        userManagementEmailSender.sendUserRegistredEmail(user, NEW_PASSWORD);

        Mockito.verify(emailMessageProducer).sendEmail(Arrays.asList(EMAIL), "Registration in PLS PRO system",
                EmailTemplates.EMAIL_HEADER + REGISTRATION_EMAIL_CONTENT + EMAIL_FOOTER, EmailType.NOT_AUDITABLE, null, null, null);
    }

    @Test@Ignore
    public void shouldSendPasswordResetEmail() throws Exception {
        final UserEntity user = getUser();

        userManagementEmailSender.sendPasswordResetEmail(user, NEW_PASSWORD);

        Mockito.verify(emailMessageProducer).sendEmail(Arrays.asList(EMAIL), "Your password in PLS system has been reset",
                EmailTemplates.EMAIL_HEADER + PASSWORD_RESET_EMAIL_CONTENT + EMAIL_FOOTER, EmailType.NOT_AUDITABLE, null, null, null);
    }

    private UserEntity getUser() {
        UserEntity user = new UserEntity();
        user.setEmail(EMAIL);
        user.setFirstName(FIRST_NAME);
        user.setLastName(LAST_NAME);
        return user;
    }

    private static final String REGISTRATION_EMAIL_CONTENT =
              "\n"
            + "<h3>Hello, " + FIRST_NAME + " " + LAST_NAME + "!</h3>\n"
            + "    <p>You were registered in PLS PRO system.</p>\n"
            + "    <p>Your password is " + NEW_PASSWORD + "</p>\n"
            + "    <p>Please, change this password after <a href=\"" + APP_URL + "\">logging in</a>.</p>\n"
            + "    <p>Sincerely, PLS Notification</p>\n"
            + "\n";
    private static final String PASSWORD_RESET_EMAIL_CONTENT =
              "\n"
            + "<h3>Hello, " + FIRST_NAME + " " + LAST_NAME + "!</h3>\n"
            + "    <p>This email message has been generated by Admin User's request to reset your password.</p>\n"
            + "    <p>Your current password is " + NEW_PASSWORD + "</p>\n"
            + "    <p>Please, change this password after <a href=\"" + APP_URL + "\">logging in</a>.</p>\n"
            + "    <p>Sincerely, PLS Notification</p>\n"
            + "\n";
    public static final String EMAIL_FOOTER =
              "        </div>\n"
            + "        <br/><br/>\n"
            + "        <div id=\"footer\">\n"
            + "            <div>\n"
            + "                <p>PLS Contact: LTL Customer Service</p>\n"
            + "                <p>Email: <a href=\"mailto:plsfreight1@plslogistics.com\">plsfreight1@plslogistics.com</a></p>\n"
            + "                <p>Phone: +1(888)757 8261</p>\n"
            + "                <p>Thank you for using <a href=\"" + APP_URL + "\">PLS Logistics Services</a></p>\n"
            + "            </div>\n"
            + "            <div id=\"logo\" class=\"left\"></div>\n"
            + "            <div id=\"printLogo\" class=\"left\">\n"
            + "                <img align=\"center\" width=\"100\" height=\"40\" src=\"http://www.plspro.com/email/pls_logo_new.jpg\"/>\n"
            + "            </div>\n"
            + "            <div id=\"headerImage\" class=\"right\"></div>\n"
            + "        </div>\n" + "    </body>\n" + "</html>";
}
