-- New Announcement
insert into ANNOUNCEMENTS (ANNOUNCEMENT_ID, START_DATE, END_DATE, THEME, TEXT, CREATED_BY, MODIFIED_BY, DATE_CREATED, DATE_MODIFIED, STATUS)
values (1, LOCALTIMESTAMP, LOCALTIMESTAMP, 'test1_theme', 'test1_text', 1, 1, LOCALTIMESTAMP, LOCALTIMESTAMP, 'U');
insert into ANNOUNCEMENTS (ANNOUNCEMENT_ID, START_DATE, END_DATE, THEME, TEXT, CREATED_BY, MODIFIED_BY, DATE_CREATED, DATE_MODIFIED, STATUS)
values (2, LOCALTIMESTAMP, LOCALTIMESTAMP, 'test2_theme', 'test2_text', 1, 1, LOCALTIMESTAMP, LOCALTIMESTAMP, 'U');
insert into ANNOUNCEMENTS (ANNOUNCEMENT_ID, START_DATE, END_DATE, THEME, TEXT, ANNOUNCER_ID, CREATED_BY, MODIFIED_BY, DATE_CREATED, DATE_MODIFIED, STATUS)
values (3, current_date, current_date + 1, 'test3_theme', 'test3_text', 1, 1, 1, LOCALTIMESTAMP, LOCALTIMESTAMP, 'P');
insert into ANNOUNCEMENTS_HISTORY (ANNOUNCEMENT_HIST_ID, ANNOUNCEMENT_ID, PERSON_ID, READ_DATE) values (1, 3, 2, LOCALTIMESTAMP);
