-- New Capabilities
INSERT INTO CAPABILITIES (CAPABILITY_ID, NAME, DESCRIPTION, ADMIN_RESTRICTED, ENABLED_FOR_ALL, CATEGORY, SYS_20, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (99999, 'CAP_NOT_ASSIGNED', 'Capability not assigned to any user', 'N', 'N', 'GEN', 'Y', -1, current_date, -1, current_date, 1);
INSERT INTO CAPABILITIES (CAPABILITY_ID, NAME, DESCRIPTION, ADMIN_RESTRICTED, ENABLED_FOR_ALL, CATEGORY, SYS_20, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (99998, 'CAP_ASSIGNED_IN_GRP', 'Capability assigned to user through group', 'N', 'N', 'GEN', 'Y', -1, current_date, -1, current_date, 1);
INSERT INTO CAPABILITIES (CAPABILITY_ID, NAME, DESCRIPTION, ADMIN_RESTRICTED, ENABLED_FOR_ALL, CATEGORY, SYS_20, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (99997, 'CAP_DIRECTLY_ASSIGNED', 'Capability directly assigned to user', 'N', 'N', 'GEN', 'Y', -1, current_date, -1, current_date, 1);
INSERT INTO CAPABILITIES (CAPABILITY_ID, NAME, DESCRIPTION, ADMIN_RESTRICTED, ENABLED_FOR_ALL, CATEGORY, SYS_20, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (99996, 'CAP_ASSIGNED_N_IN_GRP', 'Capability directly assigned to user and through group', 'N', 'N', 'GEN', 'Y', -1, current_date, -1, current_date, 1);

-- Add Capabilties to the group
INSERT INTO GROUP_CAPABILITIES (GROUP_CAPABILITY_ID, GROUP_ID, CAPABILITY_ID, STATUS, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (1051, 1, 99996, 'A', -1, current_date, -1, current_date, 1);
INSERT INTO GROUP_CAPABILITIES (GROUP_CAPABILITY_ID, GROUP_ID, CAPABILITY_ID, STATUS, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (1052, 1, 99998, 'A', -1, current_date, -1, current_date, 1);

-- Add Capabilities to users
INSERT INTO USER_CAPABILITIES_XREF (USER_CAPABILITY_ID, CAPABILITY_ID, PERSON_ID, STATUS, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (1051, 99997, 24, 'A', -1, current_date, -1, current_date, 1);
INSERT INTO USER_CAPABILITIES_XREF (USER_CAPABILITY_ID, CAPABILITY_ID, PERSON_ID, STATUS, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (1052, 99997, 25, 'A', -1, current_date, -1, current_date, 1);
INSERT INTO USER_CAPABILITIES_XREF (USER_CAPABILITY_ID, CAPABILITY_ID, PERSON_ID, STATUS, CREATED_BY, DATE_CREATED, MODIFIED_BY, DATE_MODIFIED, VERSION) VALUES (1053, 99996, 25, 'A', -1, current_date, -1, current_date, 1);
