delete from FLATBED.CAP_CATEGORY_TYPES;

INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('REPORTS', 'Reports');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('USER_MGMT', 'User Management');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('VENDOR_BILLS', 'Vendor Bills');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('MY_PROFILE', 'My Profile');

INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('ORDR', 'Orders/Shipments');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('INV' , 'Invoicing');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('RATE', 'Rating');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('GEN' , 'General');

INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('ACCOUNT_HISTORY', 'Account History');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('ADDRESS_BOOK', 'Address Book');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('PRODUCT_LIST', 'Product List');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('BOARD', 'Operational Boards');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('DASHBOARD', 'Dashboard');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('FIN_BOARD', 'Financial Board');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('CUST', 'Customer');
INSERT INTO FLATBED.CAP_CATEGORY_TYPES (CATEGORY, DESCRIPTION) VALUES ('ADMIN', 'Admin');

COMMIT;