delete from FLATBED.LD_BILL_AUDIT_REASON_CODES;

Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MS','Miscellaneous','Y','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('AD','Audit Issue','N','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('CA','Carrier Issue','N','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('RT','Rate ','N','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('FC','Freight Class','N','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('BT','Bill To','N','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('NO','PO or Other #','N','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('PW','Paperwork','N','I');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MD','Missing Document','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('CD','Cost Diff','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('LM','Low Margin','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('AC','Accessorial','N','P'); 
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('BI','Bill To','N','P'); 
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('CL','Class','N','P'); 
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('OT','Other','N','P'); 
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('WG','Weight','N','P');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('IF','Invoice Failed','N','A'); 
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('HM','High Margin','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('RL','Revenue Low','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('CS','Cost Low','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('FB','Freight Bill Date missing','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MR','Margin Review','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('HR','High Revenue Review','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('AR','Accessorial Review','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('HC','High Cost Review','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MP','Missing Payments Term','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MB','Missing BOL #','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MG','Missing GL #','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MO','Missing PO #','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MU','Missing PU #','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MZ','Missing SO #','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MH','Missing Shipper Ref #','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('MT','Missing Trailer #','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('IA','Invoice Audit required','N','A');

Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('BL','Incorrect format of BOL#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('GL','Incorrect format of GL#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('PO','Incorrect format of PO#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('UP','Incorrect format of PU#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('SO','Incorrect format of SO#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('PR','Incorrect format of Pro#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('SF','Incorrect format of Shipper Ref#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('TL','Incorrect format of Trailer#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('JB','Incorrect format of Job#','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('CV','Incorrect format of Cargo Value','N','R');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('RB','Incorrect format of Requested By','N','R');

Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('DF','Finance Review','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('DA','Dispute-Account Exec','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('DR','Dispute-Resolved','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('RP','Paperwork','N','A');
Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('RC','Cost Review complete','N','A');

Insert into FLATBED.LD_BILL_AUDIT_REASON_CODES (REASON_CD,DESCRIPTION,IS_COMMENT_REQ,REASON_TYPE) values ('CR','Ready For Consolidated','N','A'); 


COMMIT;