
INSERT INTO FLATBED.LTL_PRICING_TYPES (LTL_PRICING_TYPE,DESCRIPTION,GROUP_TYPE) VALUES ('BLANKET','Blanket','CARRIER');
INSERT INTO FLATBED.LTL_PRICING_TYPES (LTL_PRICING_TYPE,DESCRIPTION,GROUP_TYPE) VALUES ('BLANKET_CSP','Blanket/CSP','CARRIER');
INSERT INTO FLATBED.LTL_PRICING_TYPES (LTL_PRICING_TYPE,DESCRIPTION,GROUP_TYPE) VALUES ('CSP','Customer Specific Pricing (CSP)','CARRIER');
INSERT INTO FLATBED.LTL_PRICING_TYPES (LTL_PRICING_TYPE,DESCRIPTION,GROUP_TYPE) VALUES ('BUY_SELL','Buy/Sell','CARRIER');
INSERT INTO FLATBED.LTL_PRICING_TYPES (LTL_PRICING_TYPE,DESCRIPTION,GROUP_TYPE) VALUES ('BENCHMARK','Benchmark','SHIPPER');
INSERT INTO FLATBED.LTL_PRICING_TYPES (LTL_PRICING_TYPE,DESCRIPTION,GROUP_TYPE) VALUES ('MARGIN','Margin','SHIPPER');

COMMIT;