INSERT INTO FLATBED.LTL_RATING_CARRIER_TYPES (LTL_RATING_CARRIER_TYPE,DESCRIPTION) VALUES ('SMC3','SMC3');
INSERT INTO FLATBED.LTL_RATING_CARRIER_TYPES (LTL_RATING_CARRIER_TYPE,DESCRIPTION) VALUES ('MANUAL','Manual');
INSERT INTO FLATBED.LTL_RATING_CARRIER_TYPES (LTL_RATING_CARRIER_TYPE,DESCRIPTION) VALUES ('CARRIER_API','Carrier API');

COMMIT;