INSERT INTO FLATBED.MILEAGE_TYPES (MILEAGE_TYPE,MILEAGE_VERSION,DESCRIPTION,STATUS) VALUES ('MILE_MAKER','1','MileMaker','A');
INSERT INTO FLATBED.MILEAGE_TYPES (MILEAGE_TYPE,MILEAGE_VERSION,DESCRIPTION,STATUS) VALUES ('PC_MILER','1','PC Miler','A');


COMMIT;