delete from FLATBED.NOTIFICATION_TYPES;

INSERT INTO FLATBED.NOTIFICATION_TYPES (NOTIFICATION_TYPE,DESCRIPTION) VALUES ('DISPATCHED','Dispatched');
INSERT INTO FLATBED.NOTIFICATION_TYPES (NOTIFICATION_TYPE,DESCRIPTION) VALUES ('PICK_UP','Picked Up');
INSERT INTO FLATBED.NOTIFICATION_TYPES (NOTIFICATION_TYPE,DESCRIPTION) VALUES ('OUT_FOR_DELIVERY','Out For Delivery');
INSERT INTO FLATBED.NOTIFICATION_TYPES (NOTIFICATION_TYPE,DESCRIPTION) VALUES ('DELIVERED','Delivered');
INSERT INTO FLATBED.NOTIFICATION_TYPES (NOTIFICATION_TYPE,DESCRIPTION) VALUES ('DETAILS','Details');

COMMIT;
