insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (1,'Net 0',0);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (2,'Net 5 days',5);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (3,'Net 7 days',7);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (4,'Net 10 days',10);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (5,'Net 14 days',14);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (6,'Net 15 days',15);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (7,'Net 16 days',16);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (8,'Net 18 days',18);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (9,'Net 20 days',20);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (10,'Net 21 days',21);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (11,'Net 22 days',22);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (12,'Net 23 days',23);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (13,'Net 25 days',25);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (14,'Net 26 days',26);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (15,'Net 27 days',27);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (16,'Net 28 days',28);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (17,'Net 30 days',30);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (18,'Net 32 days',32);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (19,'Net 33 days',33);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (20,'Net 34 days',34);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (21,'Net 35 days',35);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (22,'Net 40 days',40);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (23,'Net 45 days',45);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (24,'Net 48 days',48);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (25,'Net 60 days',60);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (26,'Net 75 days',75);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (27,'Quick Pay 0 days',0);
insert into FLATBED.PLS_CUSTOMER_TERMS (term_id, term_name, due_days) values (28,'Quick Pay 7 days',7);