package com.pls.ax.custopenbalance.client.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source version: 2.2
 *
 * @author Thomas Clancy
 */
@WebService(name = "TriCustOpenBalanceService", targetNamespace
            = "http://schemas.microsoft.com/dynamics/2011/01/services")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
@SuppressWarnings("PMD")
public interface TriCustOpenBalanceService {

    /**
     *
     * @param parameters
     * @return returns
     * com.pls.ax.custopenbalance.client.proxy.TriCustOpenBalanceServiceGetCustOpenBalanceByAccountResponse
     * @throws TriCustOpenBalanceServiceGetCustOpenBalanceByAccountAifFaultFaultFaultMessage
     */
    @WebMethod(action
        = "http://schemas.microsoft.com/dynamics/2011/01/services/TriCustOpenBalanceService/getCustOpenBalanceByAccount")
    @WebResult(name = "TriCustOpenBalanceServiceGetCustOpenBalanceByAccountResponse", targetNamespace
               = "http://schemas.microsoft.com/dynamics/2011/01/services", partName = "parameters")
    TriCustOpenBalanceServiceGetCustOpenBalanceByAccountResponse getCustOpenBalanceByAccount(
        @WebParam(name = "TriCustOpenBalanceServiceGetCustOpenBalanceByAccountRequest",
                  targetNamespace = "http://schemas.microsoft.com/dynamics/2011/01/services",
                  partName = "parameters") TriCustOpenBalanceServiceGetCustOpenBalanceByAccountRequest parameters)
        throws TriCustOpenBalanceServiceGetCustOpenBalanceByAccountAifFaultFaultFaultMessage;

    /**
     *
     * @param parameters
     * @return returns com.pls.ax.custopenbalance.client.proxy.TriCustOpenBalanceServiceGetAllCustOpenBalancesResponse
     * @throws TriCustOpenBalanceServiceGetAllCustOpenBalancesAifFaultFaultFaultMessage
     */
    @WebMethod(action
        = "http://schemas.microsoft.com/dynamics/2011/01/services/TriCustOpenBalanceService/getAllCustOpenBalances")
    @WebResult(name = "TriCustOpenBalanceServiceGetAllCustOpenBalancesResponse", targetNamespace
               = "http://schemas.microsoft.com/dynamics/2011/01/services", partName = "parameters")
    TriCustOpenBalanceServiceGetAllCustOpenBalancesResponse getAllCustOpenBalances(
        @WebParam(name = "TriCustOpenBalanceServiceGetAllCustOpenBalancesRequest",
                  targetNamespace = "http://schemas.microsoft.com/dynamics/2011/01/services",
                  partName = "parameters") TriCustOpenBalanceServiceGetAllCustOpenBalancesRequest parameters)
        throws TriCustOpenBalanceServiceGetAllCustOpenBalancesAifFaultFaultFaultMessage;

}
