package com.pls.ax.custopenbalance.client.proxy;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source version: 2.2
 * 
 * @author Thomas Clancy
 *
 */
@WebFault(name = "AifFault", targetNamespace = "http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")
@SuppressWarnings("PMD")
public class TriCustOpenBalanceServiceGetCustOpenBalanceByAccountAifFaultFaultFaultMessage
    extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private AifFault faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public TriCustOpenBalanceServiceGetCustOpenBalanceByAccountAifFaultFaultFaultMessage(String message,
        AifFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public TriCustOpenBalanceServiceGetCustOpenBalanceByAccountAifFaultFaultFaultMessage(String message,
        AifFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return returns fault bean: com.pls.ax.custopenbalance.client.proxy.AifFault
     */
    public AifFault getFaultInfo() {
        return faultInfo;
    }

}
